import jsPDF from 'jspdf';
import type { Performance, Performer, Prop, ShowFlow } from '../types';

interface ExportData {
  title: string;
  eventDate?: string;
  showFlow: ShowFlow | null;
  performances: Record<string, Performance>;
  performers: Record<string, Performer>;
  props: Record<string, Prop>;
}

export function exportShowFlowPdf(data: ExportData) {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(data.title, margin, y);
  y += 8;

  if (data.eventDate) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Event Date: ${new Date(data.eventDate).toLocaleDateString()}`, margin, y);
    y += 4;
  }

  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, y);
  y += 10;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Show Flow
  const entries = data.showFlow?.entries || [];
  if (entries.length === 0) {
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('No show flow entries yet.', margin, y);
    y += 10;
  } else {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Show Flow', margin, y);
    y += 10;

    const totalMinutes = entries.reduce((sum, e) => sum + (e.duration_minutes || 0), 0);

    entries.forEach((entry, i) => {
      if (y > 270) {
        doc.addPage();
        y = margin;
      }

      const perf = data.performances[entry.performance_id];
      if (!perf) return;

      // Number and title
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text(`${i + 1}. ${perf.title}`, margin, y);

      // Duration
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(`${entry.duration_minutes || 0} min`, pageWidth - margin - 20, y);
      y += 6;

      // Songs
      if (perf.songs.length > 0) {
        doc.setFontSize(10);
        doc.setTextColor(80);
        doc.text(`Songs: ${perf.songs.map((s) => s.name).join(', ')}`, margin + 8, y);
        y += 5;
      }

      // Performers
      const perfPerformers = perf.performer_ids
        .map((id) => data.performers[id]?.name)
        .filter(Boolean);
      if (perfPerformers.length > 0) {
        doc.setFontSize(10);
        doc.setTextColor(80);
        doc.text(`Performers: ${perfPerformers.join(', ')}`, margin + 8, y);
        y += 5;
      }

      // Props
      const perfProps = perf.prop_ids
        .map((id) => {
          const prop = data.props[id];
          return prop ? `${prop.name} x${prop.quantity}` : null;
        })
        .filter(Boolean);
      if (perfProps.length > 0) {
        doc.setFontSize(10);
        doc.setTextColor(80);
        doc.text(`Props: ${perfProps.join(', ')}`, margin + 8, y);
        y += 5;
      }

      // Transition notes
      if (entry.transition_notes) {
        doc.setFontSize(9);
        doc.setTextColor(120);
        doc.setFont('helvetica', 'italic');
        doc.text(`Transition: ${entry.transition_notes}`, margin + 8, y);
        doc.setFont('helvetica', 'normal');
        y += 5;
      }

      y += 4;
    });

    // Total duration
    y += 4;
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text(`Total Duration: ${totalMinutes} minutes`, margin, y);
    y += 14;
  }

  // Prop checklist
  const propList = Object.values(data.props).filter((p) => p.name !== '__props_board__');
  if (propList.length > 0) {
    if (y > 250) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Prop Checklist', margin, y);
    y += 10;

    propList.forEach((prop) => {
      if (y > 280) {
        doc.addPage();
        y = margin;
      }
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0);
      const check = prop.status === 'ACQUIRED' ? '[x]' : '[ ]';
      doc.text(`${check} ${prop.name} (x${prop.quantity})`, margin + 4, y);
      y += 6;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Choreography OS', margin, doc.internal.pageSize.getHeight() - 10);

  doc.save(`${data.title.replace(/[^a-zA-Z0-9]/g, '_')}_ShowFlow.pdf`);
}
